"""estrutura inicial

Revisão: 96f32f0fc4a5
Revisão anterior: 
Criada em: 2026-08-31 13:18:09.823010+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '96f32f0fc4a5'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('plano', sa.String(length=40), nullable=False),
    sa.Column('limite_entidades', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clientes'))
    )
    op.create_table('fontes_juridicas',
    sa.Column('chave', sa.String(length=60), nullable=False),
    sa.Column('identificacao', sa.String(length=200), nullable=False),
    sa.Column('apelido', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('jurisdicao', sa.String(length=40), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('municipio', sa.String(length=120), nullable=True),
    sa.Column('orgao_emissor', sa.String(length=200), nullable=True),
    sa.Column('url_oficial', sa.String(length=500), nullable=True),
    sa.Column('ementa', sa.Text(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fontes_juridicas')),
    sa.UniqueConstraint('chave', name='uq_fonte_chave')
    )
    op.create_index(op.f('ix_fontes_juridicas_chave'), 'fontes_juridicas', ['chave'], unique=False)
    op.create_table('naturezas_juridicas',
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('sem_fins_lucrativos', sa.Boolean(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_naturezas_juridicas')),
    sa.UniqueConstraint('codigo', name=op.f('uq_naturezas_juridicas_codigo'))
    )
    op.create_table('vinculos_normativos',
    sa.Column('alvo_tipo', sa.String(length=40), nullable=False),
    sa.Column('alvo_ref', sa.String(length=120), nullable=False),
    sa.Column('fonte_chave', sa.String(length=60), nullable=False),
    sa.Column('dispositivo', sa.String(length=120), nullable=True),
    sa.Column('observacao', sa.String(length=400), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vinculos_normativos')),
    sa.UniqueConstraint('alvo_tipo', 'alvo_ref', 'fonte_chave', 'dispositivo', name='uq_vinculo_alvo_fonte')
    )
    op.create_index(op.f('ix_vinculos_normativos_alvo_ref'), 'vinculos_normativos', ['alvo_ref'], unique=False)
    op.create_index(op.f('ix_vinculos_normativos_alvo_tipo'), 'vinculos_normativos', ['alvo_tipo'], unique=False)
    op.create_index(op.f('ix_vinculos_normativos_fonte_chave'), 'vinculos_normativos', ['fonte_chave'], unique=False)
    op.create_table('configuracoes_score',
    sa.Column('cliente_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('pesos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ativa', sa.Integer(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_configuracoes_score_cliente_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuracoes_score'))
    )
    op.create_index(op.f('ix_configuracoes_score_cliente_id'), 'configuracoes_score', ['cliente_id'], unique=False)
    op.create_table('perfis',
    sa.Column('cliente_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=400), nullable=True),
    sa.Column('permissoes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('exige_habilitacao_profissional', sa.Boolean(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_perfis_cliente_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_perfis')),
    sa.UniqueConstraint('cliente_id', 'codigo', name='uq_perfis_cliente_codigo')
    )
    op.create_table('pessoas',
    sa.Column('cliente_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('orgao_expedidor', sa.String(length=20), nullable=True),
    sa.Column('nacionalidade', sa.String(length=60), nullable=True),
    sa.Column('estado_civil', sa.String(length=40), nullable=True),
    sa.Column('profissao', sa.String(length=100), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('logradouro', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=120), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('base_legal_tratamento', sa.String(length=60), nullable=True),
    sa.Column('consentimento_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_pessoas_cliente_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pessoas')),
    sa.UniqueConstraint('cliente_id', 'cpf', name='uq_pessoas_cliente_cpf')
    )
    op.create_index(op.f('ix_pessoas_cliente_id'), 'pessoas', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_pessoas_cpf'), 'pessoas', ['cpf'], unique=False)
    op.create_table('templates',
    sa.Column('cliente_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('codigo', sa.String(length=80), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo_documento', sa.String(length=40), nullable=False),
    sa.Column('tipos_entidade', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tipos_evento', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('variaveis', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('fundamentos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_templates_cliente_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates')),
    sa.UniqueConstraint('cliente_id', 'codigo', 'versao', name='uq_template_codigo_versao')
    )
    op.create_index(op.f('ix_templates_codigo'), 'templates', ['codigo'], unique=False)
    op.create_table('usuarios',
    sa.Column('cliente_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('registro_profissional', sa.String(length=50), nullable=True),
    sa.Column('uf_registro', sa.String(length=2), nullable=True),
    sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_habilitado', sa.Boolean(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_usuarios_cliente_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios'))
    )
    op.create_index(op.f('ix_usuarios_cliente_id'), 'usuarios', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('fonte_versoes',
    sa.Column('fonte_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('numero_versao', sa.Integer(), nullable=False),
    sa.Column('situacao', sa.String(length=40), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=True),
    sa.Column('vigente_ate', sa.Date(), nullable=True),
    sa.Column('publicado_em', sa.Date(), nullable=True),
    sa.Column('resumo_alteracao', sa.Text(), nullable=True),
    sa.Column('texto_referencia', sa.Text(), nullable=True),
    sa.Column('url_captura', sa.String(length=500), nullable=True),
    sa.Column('hash_conteudo', sa.String(length=64), nullable=True),
    sa.Column('origem_captura', sa.String(length=40), nullable=False),
    sa.Column('curado_por_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('curado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registro_profissional_curador', sa.String(length=30), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['curado_por_id'], ['usuarios.id'], name=op.f('fk_fonte_versoes_curado_por_id')),
    sa.ForeignKeyConstraint(['fonte_id'], ['fontes_juridicas.id'], name=op.f('fk_fonte_versoes_fonte_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fonte_versoes')),
    sa.UniqueConstraint('fonte_id', 'numero_versao', name='uq_fonte_versao_numero')
    )
    op.create_index(op.f('ix_fonte_versoes_fonte_id'), 'fonte_versoes', ['fonte_id'], unique=False)
    op.create_index(op.f('ix_fonte_versoes_vigente_desde'), 'fonte_versoes', ['vigente_desde'], unique=False)
    op.create_table('rcpj',
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('municipio', sa.String(length=120), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('contato', sa.String(length=200), nullable=True),
    sa.Column('forma_protocolo', sa.String(length=120), nullable=True),
    sa.Column('formatos_aceitos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('exige_reconhecimento_firma', sa.Boolean(), nullable=True),
    sa.Column('exige_visto_advogado', sa.Boolean(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('fonte_informacao', sa.String(length=300), nullable=True),
    sa.Column('atualizado_por_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('data_ultima_verificacao', sa.Date(), nullable=True),
    sa.Column('validade_regras_dias', sa.Integer(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['atualizado_por_id'], ['usuarios.id'], name=op.f('fk_rcpj_atualizado_por_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rcpj'))
    )
    op.create_index(op.f('ix_rcpj_municipio'), 'rcpj', ['municipio'], unique=False)
    op.create_index(op.f('ix_rcpj_uf'), 'rcpj', ['uf'], unique=False)
    op.create_table('dispositivos',
    sa.Column('versao_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('identificacao', sa.String(length=120), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('revogado', sa.Boolean(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['versao_id'], ['fonte_versoes.id'], name=op.f('fk_dispositivos_versao_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispositivos')),
    sa.UniqueConstraint('versao_id', 'identificacao', name='uq_dispositivo_versao_id')
    )
    op.create_index(op.f('ix_dispositivos_identificacao'), 'dispositivos', ['identificacao'], unique=False)
    op.create_index(op.f('ix_dispositivos_versao_id'), 'dispositivos', ['versao_id'], unique=False)
    op.create_table('entidades',
    sa.Column('cliente_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('codigo_interno', sa.String(length=30), nullable=True),
    sa.Column('razao_social', sa.String(length=300), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=300), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('natureza_juridica_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tipo_entidade', sa.String(length=40), nullable=False),
    sa.Column('data_constituicao', sa.Date(), nullable=True),
    sa.Column('data_inscricao_cnpj', sa.Date(), nullable=True),
    sa.Column('cnae_principal', sa.String(length=10), nullable=True),
    sa.Column('cnaes_secundarios', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('logradouro', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('municipio', sa.String(length=120), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('redes_sociais', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('situacao_cadastral', sa.String(length=40), nullable=True),
    sa.Column('rcpj_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_entidades_cliente_id')),
    sa.ForeignKeyConstraint(['natureza_juridica_id'], ['naturezas_juridicas.id'], name=op.f('fk_entidades_natureza_juridica_id')),
    sa.ForeignKeyConstraint(['rcpj_id'], ['rcpj.id'], name=op.f('fk_entidades_rcpj_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entidades')),
    sa.UniqueConstraint('cliente_id', 'cnpj', name='uq_entidades_cliente_cnpj')
    )
    op.create_index(op.f('ix_entidades_cliente_id'), 'entidades', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_entidades_cnpj'), 'entidades', ['cnpj'], unique=False)
    op.create_table('monitoramentos_normativos',
    sa.Column('fonte_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('rcpj_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('modo', sa.String(length=20), nullable=False),
    sa.Column('seletor', sa.String(length=200), nullable=True),
    sa.Column('periodicidade_dias', sa.Integer(), nullable=False),
    sa.Column('ultima_verificacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_hash', sa.String(length=64), nullable=True),
    sa.Column('ultimo_erro', sa.String(length=400), nullable=True),
    sa.Column('responsavel_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fonte_id'], ['fontes_juridicas.id'], name=op.f('fk_monitoramentos_normativos_fonte_id')),
    sa.ForeignKeyConstraint(['rcpj_id'], ['rcpj.id'], name=op.f('fk_monitoramentos_normativos_rcpj_id')),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], name=op.f('fk_monitoramentos_normativos_responsavel_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitoramentos_normativos'))
    )
    op.create_index(op.f('ix_monitoramentos_normativos_fonte_id'), 'monitoramentos_normativos', ['fonte_id'], unique=False)
    op.create_index(op.f('ix_monitoramentos_normativos_rcpj_id'), 'monitoramentos_normativos', ['rcpj_id'], unique=False)
    op.create_table('regras_rcpj',
    sa.Column('rcpj_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tipo_evento', sa.String(length=40), nullable=False),
    sa.Column('documentos_exigidos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('vias', sa.Integer(), nullable=True),
    sa.Column('exige_reconhecimento_firma', sa.Boolean(), nullable=True),
    sa.Column('exige_visto_advogado', sa.Boolean(), nullable=True),
    sa.Column('custas_estimadas', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('prazo_estimado_dias', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('vigente_desde', sa.Date(), nullable=True),
    sa.Column('fonte_informacao', sa.String(length=300), nullable=True),
    sa.Column('data_ultima_verificacao', sa.Date(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rcpj_id'], ['rcpj.id'], name=op.f('fk_regras_rcpj_rcpj_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regras_rcpj'))
    )
    op.create_index(op.f('ix_regras_rcpj_rcpj_id'), 'regras_rcpj', ['rcpj_id'], unique=False)
    op.create_index(op.f('ix_regras_rcpj_tipo_evento'), 'regras_rcpj', ['tipo_evento'], unique=False)
    op.create_table('associados',
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('pessoa_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('situacao', sa.String(length=40), nullable=False),
    sa.Column('direito_voto', sa.Boolean(), nullable=False),
    sa.Column('elegivel', sa.Boolean(), nullable=False),
    sa.Column('data_suspensao', sa.Date(), nullable=True),
    sa.Column('data_desligamento', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.String(length=400), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_associados_entidade_id')),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], name=op.f('fk_associados_pessoa_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_associados')),
    sa.UniqueConstraint('entidade_id', 'pessoa_id', name='uq_associado_entidade_pessoa')
    )
    op.create_index(op.f('ix_associados_entidade_id'), 'associados', ['entidade_id'], unique=False)
    op.create_index(op.f('ix_associados_pessoa_id'), 'associados', ['pessoa_id'], unique=False)
    op.create_table('atualizacoes_normativas',
    sa.Column('fonte_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('rcpj_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('monitoramento_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('origem', sa.String(length=40), nullable=False),
    sa.Column('situacao', sa.String(length=40), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('diff', sa.Text(), nullable=True),
    sa.Column('url_evidencia', sa.String(length=500), nullable=True),
    sa.Column('hash_anterior', sa.String(length=64), nullable=True),
    sa.Column('hash_novo', sa.String(length=64), nullable=True),
    sa.Column('detectado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analisado_por_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('parecer_curadoria', sa.Text(), nullable=True),
    sa.Column('publicado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fonte_versao_gerada_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analisado_por_id'], ['usuarios.id'], name=op.f('fk_atualizacoes_normativas_analisado_por_id')),
    sa.ForeignKeyConstraint(['fonte_id'], ['fontes_juridicas.id'], name=op.f('fk_atualizacoes_normativas_fonte_id')),
    sa.ForeignKeyConstraint(['fonte_versao_gerada_id'], ['fonte_versoes.id'], name=op.f('fk_atualizacoes_normativas_fonte_versao_gerada_id')),
    sa.ForeignKeyConstraint(['monitoramento_id'], ['monitoramentos_normativos.id'], name=op.f('fk_atualizacoes_normativas_monitoramento_id')),
    sa.ForeignKeyConstraint(['rcpj_id'], ['rcpj.id'], name=op.f('fk_atualizacoes_normativas_rcpj_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atualizacoes_normativas'))
    )
    op.create_index(op.f('ix_atualizacoes_normativas_fonte_id'), 'atualizacoes_normativas', ['fonte_id'], unique=False)
    op.create_index(op.f('ix_atualizacoes_normativas_situacao'), 'atualizacoes_normativas', ['situacao'], unique=False)
    op.create_table('auditoria',
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tabela', sa.String(length=80), nullable=False),
    sa.Column('registro_id', sa.String(length=60), nullable=False),
    sa.Column('operacao', sa.String(length=20), nullable=False),
    sa.Column('antes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('depois', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('usuario_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_auditoria_entidade_id')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_auditoria_usuario_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auditoria'))
    )
    op.create_index(op.f('ix_auditoria_criado_em'), 'auditoria', ['criado_em'], unique=False)
    op.create_index(op.f('ix_auditoria_entidade_id'), 'auditoria', ['entidade_id'], unique=False)
    op.create_index(op.f('ix_auditoria_registro_id'), 'auditoria', ['registro_id'], unique=False)
    op.create_index(op.f('ix_auditoria_tabela'), 'auditoria', ['tabela'], unique=False)
    op.create_table('estatutos',
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('versao_vigente_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_estatutos_entidade_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_estatutos'))
    )
    op.create_index(op.f('ix_estatutos_entidade_id'), 'estatutos', ['entidade_id'], unique=False)
    op.create_table('eventos',
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=True),
    sa.Column('dados', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('semaforo', sa.String(length=40), nullable=True),
    sa.Column('validado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resultado_validacao', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('criado_por_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], name=op.f('fk_eventos_criado_por_id')),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_eventos_entidade_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eventos'))
    )
    op.create_index(op.f('ix_eventos_entidade_id'), 'eventos', ['entidade_id'], unique=False)
    op.create_index(op.f('ix_eventos_status'), 'eventos', ['status'], unique=False)
    op.create_index(op.f('ix_eventos_tipo'), 'eventos', ['tipo'], unique=False)
    op.create_table('logs',
    sa.Column('usuario_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('acao', sa.String(length=80), nullable=False),
    sa.Column('recurso', sa.String(length=200), nullable=True),
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('resultado', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_logs_entidade_id')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_logs_usuario_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logs'))
    )
    op.create_index(op.f('ix_logs_criado_em'), 'logs', ['criado_em'], unique=False)
    op.create_index(op.f('ix_logs_usuario_id'), 'logs', ['usuario_id'], unique=False)
    op.create_table('modelos_governanca_eclesiastica',
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('denominacao', sa.String(length=200), nullable=True),
    sa.Column('convencao', sa.String(length=200), nullable=True),
    sa.Column('regras', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fonte', sa.String(length=200), nullable=True),
    sa.Column('confirmado', sa.Boolean(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_modelos_governanca_eclesiastica_entidade_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modelos_governanca_eclesiastica'))
    )
    op.create_index(op.f('ix_modelos_governanca_eclesiastica_entidade_id'), 'modelos_governanca_eclesiastica', ['entidade_id'], unique=False)
    op.create_table('orgaos',
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('orgao_pai_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('competencias', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dispositivo_estatutario', sa.String(length=120), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_orgaos_entidade_id')),
    sa.ForeignKeyConstraint(['orgao_pai_id'], ['orgaos.id'], name=op.f('fk_orgaos_orgao_pai_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orgaos'))
    )
    op.create_index(op.f('ix_orgaos_entidade_id'), 'orgaos', ['entidade_id'], unique=False)
    op.create_table('score_snapshots',
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('pontuacao', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('classificacao', sa.String(length=20), nullable=False),
    sa.Column('criterios', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('configuracao_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['configuracao_id'], ['configuracoes_score.id'], name=op.f('fk_score_snapshots_configuracao_id')),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_score_snapshots_entidade_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score_snapshots'))
    )
    op.create_index(op.f('ix_score_snapshots_data_referencia'), 'score_snapshots', ['data_referencia'], unique=False)
    op.create_index(op.f('ix_score_snapshots_entidade_id'), 'score_snapshots', ['entidade_id'], unique=False)
    op.create_table('unidades_eclesiasticas',
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('unidade_pai_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('possui_cnpj_proprio', sa.Boolean(), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('municipio', sa.String(length=120), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('responsavel_pessoa_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('data_fundacao', sa.Date(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_unidades_eclesiasticas_entidade_id')),
    sa.ForeignKeyConstraint(['responsavel_pessoa_id'], ['pessoas.id'], name=op.f('fk_unidades_eclesiasticas_responsavel_pessoa_id')),
    sa.ForeignKeyConstraint(['unidade_pai_id'], ['unidades_eclesiasticas.id'], name=op.f('fk_unidades_eclesiasticas_unidade_pai_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unidades_eclesiasticas'))
    )
    op.create_index(op.f('ix_unidades_eclesiasticas_entidade_id'), 'unidades_eclesiasticas', ['entidade_id'], unique=False)
    op.create_table('usuario_perfis',
    sa.Column('usuario_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('perfil_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_usuario_perfis_entidade_id')),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], name=op.f('fk_usuario_perfis_perfil_id')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_usuario_perfis_usuario_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario_perfis')),
    sa.UniqueConstraint('usuario_id', 'perfil_id', 'entidade_id', name='uq_usuario_perfil_entidade')
    )
    op.create_index(op.f('ix_usuario_perfis_usuario_id'), 'usuario_perfis', ['usuario_id'], unique=False)
    op.create_table('assembleias',
    sa.Column('evento_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local', sa.String(length=300), nullable=True),
    sa.Column('convocacao', sa.String(length=40), nullable=False),
    sa.Column('hora_segunda_convocacao', sa.String(length=10), nullable=True),
    sa.Column('total_aptos', sa.Integer(), nullable=True),
    sa.Column('total_presentes', sa.Integer(), nullable=True),
    sa.Column('presidida_por_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('secretariada_por_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('ordem_do_dia', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_assembleias_entidade_id')),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], name=op.f('fk_assembleias_evento_id')),
    sa.ForeignKeyConstraint(['presidida_por_id'], ['pessoas.id'], name=op.f('fk_assembleias_presidida_por_id')),
    sa.ForeignKeyConstraint(['secretariada_por_id'], ['pessoas.id'], name=op.f('fk_assembleias_secretariada_por_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assembleias'))
    )
    op.create_index(op.f('ix_assembleias_entidade_id'), 'assembleias', ['entidade_id'], unique=False)
    op.create_index(op.f('ix_assembleias_evento_id'), 'assembleias', ['evento_id'], unique=False)
    op.create_table('cargos',
    sa.Column('orgao_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('obrigatorio', sa.Boolean(), nullable=False),
    sa.Column('vagas', sa.Integer(), nullable=False),
    sa.Column('poderes_representacao', sa.Text(), nullable=True),
    sa.Column('forma_assinatura', sa.String(length=200), nullable=True),
    sa.Column('dispositivo_estatutario', sa.String(length=120), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgaos.id'], name=op.f('fk_cargos_orgao_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cargos'))
    )
    op.create_index(op.f('ix_cargos_orgao_id'), 'cargos', ['orgao_id'], unique=False)
    op.create_table('checklists',
    sa.Column('evento_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('rcpj_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('gerado_em', sa.DateTime(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], name=op.f('fk_checklists_evento_id')),
    sa.ForeignKeyConstraint(['rcpj_id'], ['rcpj.id'], name=op.f('fk_checklists_rcpj_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklists'))
    )
    op.create_index(op.f('ix_checklists_evento_id'), 'checklists', ['evento_id'], unique=False)
    op.create_table('impactos_normativos',
    sa.Column('atualizacao_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('alvo_tipo', sa.String(length=40), nullable=False),
    sa.Column('alvo_ref', sa.String(length=120), nullable=False),
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('severidade', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tratado_por_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tratado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['atualizacao_id'], ['atualizacoes_normativas.id'], name=op.f('fk_impactos_normativos_atualizacao_id')),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_impactos_normativos_entidade_id')),
    sa.ForeignKeyConstraint(['tratado_por_id'], ['usuarios.id'], name=op.f('fk_impactos_normativos_tratado_por_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impactos_normativos'))
    )
    op.create_index(op.f('ix_impactos_normativos_atualizacao_id'), 'impactos_normativos', ['atualizacao_id'], unique=False)
    op.create_table('mandatos',
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('orgao_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('designacao', sa.String(length=60), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('evento_origem_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('encerrado', sa.Boolean(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_mandatos_entidade_id')),
    sa.ForeignKeyConstraint(['evento_origem_id'], ['eventos.id'], name=op.f('fk_mandatos_evento_origem_id')),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgaos.id'], name=op.f('fk_mandatos_orgao_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mandatos'))
    )
    op.create_index(op.f('ix_mandatos_entidade_id'), 'mandatos', ['entidade_id'], unique=False)
    op.create_table('ministros',
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('pessoa_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('unidade_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('funcao', sa.String(length=40), nullable=False),
    sa.Column('data_ordenacao', sa.Date(), nullable=True),
    sa.Column('credencial', sa.String(length=80), nullable=True),
    sa.Column('orgao_credenciador', sa.String(length=200), nullable=True),
    sa.Column('situacao', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_ministros_entidade_id')),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], name=op.f('fk_ministros_pessoa_id')),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades_eclesiasticas.id'], name=op.f('fk_ministros_unidade_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ministros'))
    )
    op.create_index(op.f('ix_ministros_entidade_id'), 'ministros', ['entidade_id'], unique=False)
    op.create_index(op.f('ix_ministros_pessoa_id'), 'ministros', ['pessoa_id'], unique=False)
    op.create_table('pendencias',
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('evento_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('codigo', sa.String(length=80), nullable=True),
    sa.Column('descricao', sa.String(length=400), nullable=False),
    sa.Column('detalhamento', sa.Text(), nullable=True),
    sa.Column('prioridade', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('responsavel_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('prazo_limite', sa.Date(), nullable=True),
    sa.Column('resolvida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origem', sa.String(length=30), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_pendencias_entidade_id')),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], name=op.f('fk_pendencias_evento_id')),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], name=op.f('fk_pendencias_responsavel_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pendencias'))
    )
    op.create_index(op.f('ix_pendencias_codigo'), 'pendencias', ['codigo'], unique=False)
    op.create_index(op.f('ix_pendencias_entidade_id'), 'pendencias', ['entidade_id'], unique=False)
    op.create_index(op.f('ix_pendencias_evento_id'), 'pendencias', ['evento_id'], unique=False)
    op.create_index(op.f('ix_pendencias_prioridade'), 'pendencias', ['prioridade'], unique=False)
    op.create_index(op.f('ix_pendencias_status'), 'pendencias', ['status'], unique=False)
    op.create_table('protocolos',
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('evento_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('rcpj_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('numero', sa.String(length=60), nullable=True),
    sa.Column('data_protocolo', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('exigencias', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('numero_registro', sa.String(length=60), nullable=True),
    sa.Column('livro', sa.String(length=30), nullable=True),
    sa.Column('folha', sa.String(length=30), nullable=True),
    sa.Column('custas', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_protocolos_entidade_id')),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], name=op.f('fk_protocolos_evento_id')),
    sa.ForeignKeyConstraint(['rcpj_id'], ['rcpj.id'], name=op.f('fk_protocolos_rcpj_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_protocolos'))
    )
    op.create_index(op.f('ix_protocolos_entidade_id'), 'protocolos', ['entidade_id'], unique=False)
    op.create_index(op.f('ix_protocolos_evento_id'), 'protocolos', ['evento_id'], unique=False)
    op.create_table('deliberacoes',
    sa.Column('assembleia_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('materia', sa.String(length=400), nullable=False),
    sa.Column('chave_quorum', sa.String(length=80), nullable=True),
    sa.Column('votos_favor', sa.Integer(), nullable=True),
    sa.Column('votos_contra', sa.Integer(), nullable=True),
    sa.Column('abstencoes', sa.Integer(), nullable=True),
    sa.Column('aprovada', sa.Boolean(), nullable=True),
    sa.Column('texto_deliberacao', sa.Text(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assembleia_id'], ['assembleias.id'], name=op.f('fk_deliberacoes_assembleia_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliberacoes'))
    )
    op.create_index(op.f('ix_deliberacoes_assembleia_id'), 'deliberacoes', ['assembleia_id'], unique=False)
    op.create_table('documentos',
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('evento_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('categoria', sa.String(length=40), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('data_documento', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('versao_atual', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('protocolo_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('template_codigo', sa.String(length=80), nullable=True),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_documentos_entidade_id')),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], name=op.f('fk_documentos_evento_id')),
    sa.ForeignKeyConstraint(['protocolo_id'], ['protocolos.id'], name=op.f('fk_documentos_protocolo_id')),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], name=op.f('fk_documentos_responsavel_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documentos'))
    )
    op.create_index(op.f('ix_documentos_entidade_id'), 'documentos', ['entidade_id'], unique=False)
    op.create_index(op.f('ix_documentos_evento_id'), 'documentos', ['evento_id'], unique=False)
    op.create_index(op.f('ix_documentos_status'), 'documentos', ['status'], unique=False)
    op.create_table('linha_tempo',
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('evento_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('protocolo_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('documentos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_linha_tempo_entidade_id')),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], name=op.f('fk_linha_tempo_evento_id')),
    sa.ForeignKeyConstraint(['protocolo_id'], ['protocolos.id'], name=op.f('fk_linha_tempo_protocolo_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_linha_tempo'))
    )
    op.create_index(op.f('ix_linha_tempo_data'), 'linha_tempo', ['data'], unique=False)
    op.create_index(op.f('ix_linha_tempo_entidade_id'), 'linha_tempo', ['entidade_id'], unique=False)
    op.create_table('certidoes',
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tipo', sa.String(length=120), nullable=False),
    sa.Column('orgao_emissor', sa.String(length=150), nullable=True),
    sa.Column('numero', sa.String(length=80), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('documento_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('observacoes', sa.String(length=400), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], name=op.f('fk_certidoes_documento_id')),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_certidoes_entidade_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certidoes'))
    )
    op.create_index(op.f('ix_certidoes_data_validade'), 'certidoes', ['data_validade'], unique=False)
    op.create_index(op.f('ix_certidoes_entidade_id'), 'certidoes', ['entidade_id'], unique=False)
    op.create_table('checklist_itens',
    sa.Column('checklist_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('obrigatorio', sa.Boolean(), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('fundamento', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('documento_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], name=op.f('fk_checklist_itens_checklist_id')),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], name=op.f('fk_checklist_itens_documento_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_itens'))
    )
    op.create_index(op.f('ix_checklist_itens_checklist_id'), 'checklist_itens', ['checklist_id'], unique=False)
    op.create_table('convocacoes',
    sa.Column('assembleia_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('data_publicacao', sa.Date(), nullable=False),
    sa.Column('meio', sa.String(length=120), nullable=True),
    sa.Column('convocado_por_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('orgao_convocante_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('documento_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assembleia_id'], ['assembleias.id'], name=op.f('fk_convocacoes_assembleia_id')),
    sa.ForeignKeyConstraint(['convocado_por_id'], ['pessoas.id'], name=op.f('fk_convocacoes_convocado_por_id')),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], name=op.f('fk_convocacoes_documento_id')),
    sa.ForeignKeyConstraint(['orgao_convocante_id'], ['orgaos.id'], name=op.f('fk_convocacoes_orgao_convocante_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_convocacoes'))
    )
    op.create_index(op.f('ix_convocacoes_assembleia_id'), 'convocacoes', ['assembleia_id'], unique=False)
    op.create_table('documento_versoes',
    sa.Column('documento_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('arquivo_path', sa.String(length=500), nullable=True),
    sa.Column('formato', sa.String(length=10), nullable=False),
    sa.Column('hash_conteudo', sa.String(length=64), nullable=True),
    sa.Column('template_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('dados_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('lacunas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fundamentos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('gerado_por_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('motivo', sa.String(length=400), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], name=op.f('fk_documento_versoes_documento_id')),
    sa.ForeignKeyConstraint(['gerado_por_id'], ['usuarios.id'], name=op.f('fk_documento_versoes_gerado_por_id')),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name=op.f('fk_documento_versoes_template_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documento_versoes')),
    sa.UniqueConstraint('documento_id', 'numero', name='uq_documento_versao_numero')
    )
    op.create_index(op.f('ix_documento_versoes_documento_id'), 'documento_versoes', ['documento_id'], unique=False)
    op.create_table('estatuto_versoes',
    sa.Column('estatuto_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('numero_versao', sa.Integer(), nullable=False),
    sa.Column('data_estatuto', sa.Date(), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('numero_registro', sa.String(length=50), nullable=True),
    sa.Column('livro', sa.String(length=30), nullable=True),
    sa.Column('folha', sa.String(length=30), nullable=True),
    sa.Column('rcpj_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('municipio', sa.String(length=120), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('documento_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.Column('evento_origem_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('motivo_alteracao', sa.String(length=400), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], name=op.f('fk_estatuto_versoes_documento_id')),
    sa.ForeignKeyConstraint(['estatuto_id'], ['estatutos.id'], name=op.f('fk_estatuto_versoes_estatuto_id')),
    sa.ForeignKeyConstraint(['evento_origem_id'], ['eventos.id'], name=op.f('fk_estatuto_versoes_evento_origem_id')),
    sa.ForeignKeyConstraint(['rcpj_id'], ['rcpj.id'], name=op.f('fk_estatuto_versoes_rcpj_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_estatuto_versoes')),
    sa.UniqueConstraint('estatuto_id', 'numero_versao', name='uq_estatuto_versao')
    )
    op.create_index(op.f('ix_estatuto_versoes_estatuto_id'), 'estatuto_versoes', ['estatuto_id'], unique=False)
    op.create_table('listas_presenca',
    sa.Column('assembleia_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('pessoa_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('apto_a_votar', sa.Boolean(), nullable=False),
    sa.Column('representado_por_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('procuracao_documento_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assembleia_id'], ['assembleias.id'], name=op.f('fk_listas_presenca_assembleia_id')),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], name=op.f('fk_listas_presenca_pessoa_id')),
    sa.ForeignKeyConstraint(['procuracao_documento_id'], ['documentos.id'], name=op.f('fk_listas_presenca_procuracao_documento_id')),
    sa.ForeignKeyConstraint(['representado_por_id'], ['pessoas.id'], name=op.f('fk_listas_presenca_representado_por_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listas_presenca'))
    )
    op.create_index(op.f('ix_listas_presenca_assembleia_id'), 'listas_presenca', ['assembleia_id'], unique=False)
    op.create_table('mandato_membros',
    sa.Column('mandato_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('pessoa_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('cargo_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('situacao', sa.String(length=40), nullable=False),
    sa.Column('documento_eleicao_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('documento_posse_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('protocolo_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('observacoes', sa.String(length=400), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], name=op.f('fk_mandato_membros_cargo_id')),
    sa.ForeignKeyConstraint(['documento_eleicao_id'], ['documentos.id'], name=op.f('fk_mandato_membros_documento_eleicao_id')),
    sa.ForeignKeyConstraint(['documento_posse_id'], ['documentos.id'], name=op.f('fk_mandato_membros_documento_posse_id')),
    sa.ForeignKeyConstraint(['mandato_id'], ['mandatos.id'], name=op.f('fk_mandato_membros_mandato_id')),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], name=op.f('fk_mandato_membros_pessoa_id')),
    sa.ForeignKeyConstraint(['protocolo_id'], ['protocolos.id'], name=op.f('fk_mandato_membros_protocolo_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mandato_membros'))
    )
    op.create_index(op.f('ix_mandato_membros_mandato_id'), 'mandato_membros', ['mandato_id'], unique=False)
    op.create_index(op.f('ix_mandato_membros_pessoa_id'), 'mandato_membros', ['pessoa_id'], unique=False)
    op.create_table('analises_ia',
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('documento_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('estatuto_versao_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('solicitado_por_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('concluida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], name=op.f('fk_analises_ia_documento_id')),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_analises_ia_entidade_id')),
    sa.ForeignKeyConstraint(['estatuto_versao_id'], ['estatuto_versoes.id'], name=op.f('fk_analises_ia_estatuto_versao_id')),
    sa.ForeignKeyConstraint(['solicitado_por_id'], ['usuarios.id'], name=op.f('fk_analises_ia_solicitado_por_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analises_ia'))
    )
    op.create_index(op.f('ix_analises_ia_entidade_id'), 'analises_ia', ['entidade_id'], unique=False)
    op.create_table('assinaturas',
    sa.Column('documento_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('documento_versao_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('pessoa_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('nome_signatario', sa.String(length=200), nullable=False),
    sa.Column('papel', sa.String(length=120), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('exige_reconhecimento_firma', sa.Boolean(), nullable=False),
    sa.Column('data_assinatura', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provedor', sa.String(length=60), nullable=True),
    sa.Column('evidencia', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], name=op.f('fk_assinaturas_documento_id')),
    sa.ForeignKeyConstraint(['documento_versao_id'], ['documento_versoes.id'], name=op.f('fk_assinaturas_documento_versao_id')),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], name=op.f('fk_assinaturas_pessoa_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assinaturas'))
    )
    op.create_index(op.f('ix_assinaturas_documento_id'), 'assinaturas', ['documento_id'], unique=False)
    op.create_table('estatuto_parametros',
    sa.Column('versao_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('chave', sa.String(length=80), nullable=False),
    sa.Column('valor', sa.String(length=400), nullable=True),
    sa.Column('tipo_valor', sa.String(length=20), nullable=False),
    sa.Column('unidade', sa.String(length=30), nullable=True),
    sa.Column('dispositivo', sa.String(length=120), nullable=True),
    sa.Column('trecho', sa.Text(), nullable=True),
    sa.Column('origem', sa.String(length=40), nullable=False),
    sa.Column('confianca', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('confirmado', sa.Boolean(), nullable=False),
    sa.Column('confirmado_por_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('confirmado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacao', sa.String(length=400), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['confirmado_por_id'], ['usuarios.id'], name=op.f('fk_estatuto_parametros_confirmado_por_id')),
    sa.ForeignKeyConstraint(['versao_id'], ['estatuto_versoes.id'], name=op.f('fk_estatuto_parametros_versao_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_estatuto_parametros')),
    sa.UniqueConstraint('versao_id', 'chave', name='uq_parametro_versao_chave')
    )
    op.create_index(op.f('ix_estatuto_parametros_chave'), 'estatuto_parametros', ['chave'], unique=False)
    op.create_index(op.f('ix_estatuto_parametros_versao_id'), 'estatuto_parametros', ['versao_id'], unique=False)
    op.create_table('prazos',
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('data_base', sa.Date(), nullable=True),
    sa.Column('data_limite', sa.Date(), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('fundamento', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('janelas_alerta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('alertas_disparados', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evento_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('mandato_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('protocolo_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('certidao_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('responsavel_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('chave_idempotencia', sa.String(length=120), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['certidao_id'], ['certidoes.id'], name=op.f('fk_prazos_certidao_id')),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_prazos_entidade_id')),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], name=op.f('fk_prazos_evento_id')),
    sa.ForeignKeyConstraint(['mandato_id'], ['mandatos.id'], name=op.f('fk_prazos_mandato_id')),
    sa.ForeignKeyConstraint(['protocolo_id'], ['protocolos.id'], name=op.f('fk_prazos_protocolo_id')),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], name=op.f('fk_prazos_responsavel_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prazos'))
    )
    op.create_index(op.f('ix_prazos_chave_idempotencia'), 'prazos', ['chave_idempotencia'], unique=False)
    op.create_index(op.f('ix_prazos_data_limite'), 'prazos', ['data_limite'], unique=False)
    op.create_index(op.f('ix_prazos_entidade_id'), 'prazos', ['entidade_id'], unique=False)
    op.create_index(op.f('ix_prazos_status'), 'prazos', ['status'], unique=False)
    op.create_index(op.f('ix_prazos_tipo'), 'prazos', ['tipo'], unique=False)
    op.create_table('notificacoes',
    sa.Column('usuario_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('entidade_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('prazo_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('pendencia_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('enviada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entidade_id'], ['entidades.id'], name=op.f('fk_notificacoes_entidade_id')),
    sa.ForeignKeyConstraint(['pendencia_id'], ['pendencias.id'], name=op.f('fk_notificacoes_pendencia_id')),
    sa.ForeignKeyConstraint(['prazo_id'], ['prazos.id'], name=op.f('fk_notificacoes_prazo_id')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_notificacoes_usuario_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notificacoes'))
    )
    op.create_index(op.f('ix_notificacoes_usuario_id'), 'notificacoes', ['usuario_id'], unique=False)
    op.create_table('pareceres_juridicos',
    sa.Column('evento_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('responsavel_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('registro_oab', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('ressalvas', sa.Text(), nullable=True),
    sa.Column('data_parecer', sa.Date(), nullable=True),
    sa.Column('assinatura_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assinatura_id'], ['assinaturas.id'], name=op.f('fk_pareceres_juridicos_assinatura_id')),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], name=op.f('fk_pareceres_juridicos_evento_id')),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], name=op.f('fk_pareceres_juridicos_responsavel_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pareceres_juridicos'))
    )
    op.create_index(op.f('ix_pareceres_juridicos_evento_id'), 'pareceres_juridicos', ['evento_id'], unique=False)
    op.create_table('sugestoes_ia',
    sa.Column('analise_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('chave', sa.String(length=80), nullable=False),
    sa.Column('valor_sugerido', sa.String(length=400), nullable=True),
    sa.Column('dispositivo', sa.String(length=120), nullable=True),
    sa.Column('trecho', sa.Text(), nullable=True),
    sa.Column('confianca', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('pergunta_validacao', sa.String(length=400), nullable=True),
    sa.Column('aceita_por_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('aceita_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadados', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aceita_por_id'], ['usuarios.id'], name=op.f('fk_sugestoes_ia_aceita_por_id')),
    sa.ForeignKeyConstraint(['analise_id'], ['analises_ia.id'], name=op.f('fk_sugestoes_ia_analise_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sugestoes_ia'))
    )
    op.create_index(op.f('ix_sugestoes_ia_analise_id'), 'sugestoes_ia', ['analise_id'], unique=False)
    op.create_index(op.f('ix_sugestoes_ia_chave'), 'sugestoes_ia', ['chave'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sugestoes_ia_chave'), table_name='sugestoes_ia')
    op.drop_index(op.f('ix_sugestoes_ia_analise_id'), table_name='sugestoes_ia')
    op.drop_table('sugestoes_ia')
    op.drop_index(op.f('ix_pareceres_juridicos_evento_id'), table_name='pareceres_juridicos')
    op.drop_table('pareceres_juridicos')
    op.drop_index(op.f('ix_notificacoes_usuario_id'), table_name='notificacoes')
    op.drop_table('notificacoes')
    op.drop_index(op.f('ix_prazos_tipo'), table_name='prazos')
    op.drop_index(op.f('ix_prazos_status'), table_name='prazos')
    op.drop_index(op.f('ix_prazos_entidade_id'), table_name='prazos')
    op.drop_index(op.f('ix_prazos_data_limite'), table_name='prazos')
    op.drop_index(op.f('ix_prazos_chave_idempotencia'), table_name='prazos')
    op.drop_table('prazos')
    op.drop_index(op.f('ix_estatuto_parametros_versao_id'), table_name='estatuto_parametros')
    op.drop_index(op.f('ix_estatuto_parametros_chave'), table_name='estatuto_parametros')
    op.drop_table('estatuto_parametros')
    op.drop_index(op.f('ix_assinaturas_documento_id'), table_name='assinaturas')
    op.drop_table('assinaturas')
    op.drop_index(op.f('ix_analises_ia_entidade_id'), table_name='analises_ia')
    op.drop_table('analises_ia')
    op.drop_index(op.f('ix_mandato_membros_pessoa_id'), table_name='mandato_membros')
    op.drop_index(op.f('ix_mandato_membros_mandato_id'), table_name='mandato_membros')
    op.drop_table('mandato_membros')
    op.drop_index(op.f('ix_listas_presenca_assembleia_id'), table_name='listas_presenca')
    op.drop_table('listas_presenca')
    op.drop_index(op.f('ix_estatuto_versoes_estatuto_id'), table_name='estatuto_versoes')
    op.drop_table('estatuto_versoes')
    op.drop_index(op.f('ix_documento_versoes_documento_id'), table_name='documento_versoes')
    op.drop_table('documento_versoes')
    op.drop_index(op.f('ix_convocacoes_assembleia_id'), table_name='convocacoes')
    op.drop_table('convocacoes')
    op.drop_index(op.f('ix_checklist_itens_checklist_id'), table_name='checklist_itens')
    op.drop_table('checklist_itens')
    op.drop_index(op.f('ix_certidoes_entidade_id'), table_name='certidoes')
    op.drop_index(op.f('ix_certidoes_data_validade'), table_name='certidoes')
    op.drop_table('certidoes')
    op.drop_index(op.f('ix_linha_tempo_entidade_id'), table_name='linha_tempo')
    op.drop_index(op.f('ix_linha_tempo_data'), table_name='linha_tempo')
    op.drop_table('linha_tempo')
    op.drop_index(op.f('ix_documentos_status'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_evento_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_entidade_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_deliberacoes_assembleia_id'), table_name='deliberacoes')
    op.drop_table('deliberacoes')
    op.drop_index(op.f('ix_protocolos_evento_id'), table_name='protocolos')
    op.drop_index(op.f('ix_protocolos_entidade_id'), table_name='protocolos')
    op.drop_table('protocolos')
    op.drop_index(op.f('ix_pendencias_status'), table_name='pendencias')
    op.drop_index(op.f('ix_pendencias_prioridade'), table_name='pendencias')
    op.drop_index(op.f('ix_pendencias_evento_id'), table_name='pendencias')
    op.drop_index(op.f('ix_pendencias_entidade_id'), table_name='pendencias')
    op.drop_index(op.f('ix_pendencias_codigo'), table_name='pendencias')
    op.drop_table('pendencias')
    op.drop_index(op.f('ix_ministros_pessoa_id'), table_name='ministros')
    op.drop_index(op.f('ix_ministros_entidade_id'), table_name='ministros')
    op.drop_table('ministros')
    op.drop_index(op.f('ix_mandatos_entidade_id'), table_name='mandatos')
    op.drop_table('mandatos')
    op.drop_index(op.f('ix_impactos_normativos_atualizacao_id'), table_name='impactos_normativos')
    op.drop_table('impactos_normativos')
    op.drop_index(op.f('ix_checklists_evento_id'), table_name='checklists')
    op.drop_table('checklists')
    op.drop_index(op.f('ix_cargos_orgao_id'), table_name='cargos')
    op.drop_table('cargos')
    op.drop_index(op.f('ix_assembleias_evento_id'), table_name='assembleias')
    op.drop_index(op.f('ix_assembleias_entidade_id'), table_name='assembleias')
    op.drop_table('assembleias')
    op.drop_index(op.f('ix_usuario_perfis_usuario_id'), table_name='usuario_perfis')
    op.drop_table('usuario_perfis')
    op.drop_index(op.f('ix_unidades_eclesiasticas_entidade_id'), table_name='unidades_eclesiasticas')
    op.drop_table('unidades_eclesiasticas')
    op.drop_index(op.f('ix_score_snapshots_entidade_id'), table_name='score_snapshots')
    op.drop_index(op.f('ix_score_snapshots_data_referencia'), table_name='score_snapshots')
    op.drop_table('score_snapshots')
    op.drop_index(op.f('ix_orgaos_entidade_id'), table_name='orgaos')
    op.drop_table('orgaos')
    op.drop_index(op.f('ix_modelos_governanca_eclesiastica_entidade_id'), table_name='modelos_governanca_eclesiastica')
    op.drop_table('modelos_governanca_eclesiastica')
    op.drop_index(op.f('ix_logs_usuario_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_criado_em'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_eventos_tipo'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_status'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_entidade_id'), table_name='eventos')
    op.drop_table('eventos')
    op.drop_index(op.f('ix_estatutos_entidade_id'), table_name='estatutos')
    op.drop_table('estatutos')
    op.drop_index(op.f('ix_auditoria_tabela'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_registro_id'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_entidade_id'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_criado_em'), table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_index(op.f('ix_atualizacoes_normativas_situacao'), table_name='atualizacoes_normativas')
    op.drop_index(op.f('ix_atualizacoes_normativas_fonte_id'), table_name='atualizacoes_normativas')
    op.drop_table('atualizacoes_normativas')
    op.drop_index(op.f('ix_associados_pessoa_id'), table_name='associados')
    op.drop_index(op.f('ix_associados_entidade_id'), table_name='associados')
    op.drop_table('associados')
    op.drop_index(op.f('ix_regras_rcpj_tipo_evento'), table_name='regras_rcpj')
    op.drop_index(op.f('ix_regras_rcpj_rcpj_id'), table_name='regras_rcpj')
    op.drop_table('regras_rcpj')
    op.drop_index(op.f('ix_monitoramentos_normativos_rcpj_id'), table_name='monitoramentos_normativos')
    op.drop_index(op.f('ix_monitoramentos_normativos_fonte_id'), table_name='monitoramentos_normativos')
    op.drop_table('monitoramentos_normativos')
    op.drop_index(op.f('ix_entidades_cnpj'), table_name='entidades')
    op.drop_index(op.f('ix_entidades_cliente_id'), table_name='entidades')
    op.drop_table('entidades')
    op.drop_index(op.f('ix_dispositivos_versao_id'), table_name='dispositivos')
    op.drop_index(op.f('ix_dispositivos_identificacao'), table_name='dispositivos')
    op.drop_table('dispositivos')
    op.drop_index(op.f('ix_rcpj_uf'), table_name='rcpj')
    op.drop_index(op.f('ix_rcpj_municipio'), table_name='rcpj')
    op.drop_table('rcpj')
    op.drop_index(op.f('ix_fonte_versoes_vigente_desde'), table_name='fonte_versoes')
    op.drop_index(op.f('ix_fonte_versoes_fonte_id'), table_name='fonte_versoes')
    op.drop_table('fonte_versoes')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cliente_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_templates_codigo'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_pessoas_cpf'), table_name='pessoas')
    op.drop_index(op.f('ix_pessoas_cliente_id'), table_name='pessoas')
    op.drop_table('pessoas')
    op.drop_table('perfis')
    op.drop_index(op.f('ix_configuracoes_score_cliente_id'), table_name='configuracoes_score')
    op.drop_table('configuracoes_score')
    op.drop_index(op.f('ix_vinculos_normativos_fonte_chave'), table_name='vinculos_normativos')
    op.drop_index(op.f('ix_vinculos_normativos_alvo_tipo'), table_name='vinculos_normativos')
    op.drop_index(op.f('ix_vinculos_normativos_alvo_ref'), table_name='vinculos_normativos')
    op.drop_table('vinculos_normativos')
    op.drop_table('naturezas_juridicas')
    op.drop_index(op.f('ix_fontes_juridicas_chave'), table_name='fontes_juridicas')
    op.drop_table('fontes_juridicas')
    op.drop_table('clientes')
    # ### end Alembic commands ###
