"""agendador registro de execucoes

Revisão: 2c80f7235b0a
Revisão anterior: 96f32f0fc4a5
Criada em: 2026-09-01 17:57:46.146350+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2c80f7235b0a'
down_revision: str | None = '96f32f0fc4a5'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execucoes_agendador',
    sa.Column('tarefa', sa.String(length=40), nullable=False),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('concluida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resultado', sa.String(length=10), nullable=False),
    sa.Column('numeros', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('falhas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.Column('acionada_por', sa.String(length=20), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execucoes_agendador'))
    )
    op.create_index(op.f('ix_execucoes_agendador_iniciada_em'), 'execucoes_agendador', ['iniciada_em'], unique=False)
    op.create_index(op.f('ix_execucoes_agendador_resultado'), 'execucoes_agendador', ['resultado'], unique=False)
    op.create_index(op.f('ix_execucoes_agendador_tarefa'), 'execucoes_agendador', ['tarefa'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execucoes_agendador_tarefa'), table_name='execucoes_agendador')
    op.drop_index(op.f('ix_execucoes_agendador_resultado'), table_name='execucoes_agendador')
    op.drop_index(op.f('ix_execucoes_agendador_iniciada_em'), table_name='execucoes_agendador')
    op.drop_table('execucoes_agendador')
    # ### end Alembic commands ###
